ZEPPELIN_SPARK_MAXRESULT=10000
ZEPPELIN_JAVA_OPTS=" -Djava.util.Arrays.useLegacyMergeSort=true -Dspark.executor.memory=2g -Dspark.cores.max=2  "
ZEPPELIN_SERVER_PORT=12345
ZEPPELIN_SPARK_DRIVER_MEMORY="512M"
ZEPPELIN_SPARK_UI_PORT=4040
